{"name": "test_negative_create_new_task[invalid_data2-401-You do not have access to this task-ACCESS_083]", "status": "passed", "description": "Create task with wrong name, parent ID, link ID and validate that errors are equal to expected", "steps": [{"name": "Create new task with body: {'name': 'want', 'links_to': 366}, expected status code: 401", "status": "passed", "steps": [{"name": "Create url with base url and endpoint: /list/901510919856/task", "status": "passed", "start": 1746873210626, "stop": 1746873210626}, {"name": "Send POST request to https://api.clickup.com/api/v2/list/901510919856/task with {'name': 'want', 'links_to': 366}None, expected status code 401", "status": "passed", "start": 1746873210626, "stop": 1746873211149}], "start": 1746873210626, "stop": 1746873211149}], "parameters": [{"name": "invalid_data", "value": "{'name': 'want', 'links_to': 366}"}, {"name": "expected_status_code", "value": "401"}, {"name": "expected_err_message", "value": "'You do not have access to this task'"}, {"name": "expected_err_code", "value": "'ACCESS_083'"}], "start": 1746873210626, "stop": 1746873211150, "uuid": "2a839201-2ed7-44cd-957b-9708f1eb553c", "historyId": "869d27894aa5854a13106053c3ff029b", "testCaseId": "2b634744f349a3d06f3aee13d601988d", "fullName": "tests.api.test_tasks.TestTasks#test_negative_create_new_task", "labels": [{"name": "feature", "value": "Manage tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "apachai"}, {"name": "thread", "value": "19032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}